// solidIngredient["Salt"] = "images/solidos/salt.png";
const solidIngredient = {
     "Anis": "images/solidos/Anis.png",
     "Apple": "images/solidos/Apple.png",
     "Banana": "images/solidos/Banana.png",
     "Blackberries": "images/solidos/Blackberries.png",
     "Blood Orange": "images/solidos/Blood Orange.png",
     "Brown Sugar": "images/solidos/Brown Sugar.png",
     "Cardamon": "images/solidos/Cardamon.png",
     "Celery salt": "images/solidos/Celery salt.png",
     "Cherry": "images/solidos/Cherry.png",
     "Chocolate": "images/solidos/Chocolate.png",
     "Cinnamon": "images/solidos/Cinnamon.png",
     "Cloves": "images/solidos/cloves.png",
     "Cocoa powder": "images/solidos/Cocoa powder.png",
     "Cucumber": "images/solidos/Cucumber.png",
     "Egg white": "images/solidos/Egg white.png",  //ponderar 
     "Egg": "images/solidos/Egg.png",   //ponderar
     "Figs": "images/solidos/Figs.png",
     "Ginger": "images/solidos/Ginger.png",
     "Honey": "images/solidos/Honey.png",
     "Ice": "images/solidos/Ice.png",
     "Kiwi": "images/solidos/Kiwi.png",
     "Lemon peel": "images/solidos/Lemon peel.png",
     "Lemon": "images/solidos/Lemon.png",
     "Lime peel": "images/solidos/Lime peel.png",
     "Lime": "images/solidos/Lime.png",
     "Mint": "images/solidos/Mint.png",
     "Nutmeg": "images/solidos/Nutmeg.png",
     "Olive": "images/solidos/Olive.png",
     "Orange peel": "images/solidos/Orange peel.png",
     "Orange spiral": "images/solidos/Orange spiral.png",
     "Orange": "images/solidos/Orange.png",
     "Oreo cookie": "images/solidos/Oreo cookie.png",
     "Papaya": "images/solidos/Papaya.png",
     "Pepper": "images/solidos/Pepper.png",
     "Pineapple": "images/solidos/Pineapple.png",
     "Powdered sugar": "images/solidos/Powdered sugar.png",
     "Salt": "images/solidos/Salt.png",
     "Strawberry": "images/solidos/Strawberry.png",
     "Sugar": "images/solidos/Sugar.png",
     "Thyme": "images/solidos/Thyme.png",
     "Vanilla": "images/solidos/Vanilla.png",
     "Wormwood": "images/solidos/Wormwood.png"
};
